package com.eva.reminders.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xff005cbb)
val LightSecondary = Color(0xff565e71)
val LightTertiary = Color(0xff984800)
val LightError = Color(0xffba1a1a)
val LightBackGround = Color(0xfffdfbff)
val LightOnBackGround = Color(0xff1a1b1f)
val LightOnError = Color(0xffffffff)
val LightOnTertiary = Color(0xffffffff)
val LightOnSecondary = Color(0xffffffff)
val LightOnPrimary = Color(0xffffffff)
val LightPrimaryContainer = Color(0xffd7e3ff)
val LightSecondaryContainer = Color(0xffdae2f9)
val LightTertiaryContainer = Color(0xffffdbc8)
val LightOnPrimaryContainer = Color(0xff001b3f)
val LightOnSecondaryContainer = Color(0xff131c2b)
val LightOnTertiaryContainer = Color(0xff321300)
val LightErrorContainer = Color(0xffffdad6)
val LightOnErrorContainer = Color(0xff410002)
val LightSurface = Color(0xfffdfbff)
val LightOnSurface = Color(0xff1a1b1f)
val LightSurfaceVariant = Color(0xffe0e2ec)
val LightOnSurfaceVariant = Color(0xff44474e)
val LightOutlined = Color(0xff74777f)

val DarkPrimary = Color(0xffabc7ff)
val DarkSecondary = Color(0xffbec6dc)
val DarkTertiary = Color(0xffffb689)
val DarkError = Color(0xffffb4ab)
val DarkBackGround = Color(0xff1a1b1f)
val DarkOnBackGround = Color(0xffe3e2e6)
val DarkOnError = Color(0xff690005)
val DarkOnTertiary = Color(0xff512300)
val DarkOnSecondary = Color(0xff283041)
val DarkOnPrimary = Color(0xff002f65)
val DarkPrimaryContainer = Color(0xff00458f)
val DarkSecondaryContainer = Color(0xff3e4759)
val DarkTertiaryContainer = Color(0xff743500)
val DarkOnPrimaryContainer = Color(0xffd7e3ff)
val DarkOnSecondaryContainer = Color(0xffdae2f9)
val DarkOnTertiaryContainer = Color(0xffffdbc8)
val DarkErrorContainer = Color(0xff93000a)
val DarkOnErrorContainer = Color(0xffffdad6)
val DarkSurface = Color(0xff1a1b1f)
val DarkOnSurface = Color(0xffe3e2e6)
val DarkSurfaceVariant = Color(0xff44474e)
val DarkOnSurfaceVariant = Color(0xffc4c6d0)
val DarkOutlined = Color(0xff8e9099)